name: stream_bloc
description: Modern implementation of the Original BLoC that uses asynchronous generators to describe relationships between events and states.
version: 0.2.0
repository: https://github.com/purplenoodlesoop/stream-bloc
issue_tracker: https://github.com/purplenoodlesoop/stream-bloc/issues
homepage: https://github.com/purplenoodlesoop/stream-bloc
documentation: https://github.com/purplenoodlesoop/stream-bloc/blob/master/README.md

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  meta: ^1.7.0
  bloc: ^8.0.2


