name: stream_bloc
description: Modern implementation of the Original BLoC that uses asynchronous generators to describe relationships between events and states.
version: 0.6.0
repository: https://github.com/purplenoodlesoop/stream-bloc
issue_tracker: https://github.com/purplenoodlesoop/stream-bloc/issues
homepage: https://github.com/purplenoodlesoop/stream-bloc
documentation: https://github.com/purplenoodlesoop/stream-bloc/blob/master/README.md

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  meta: ^1.8.0
  bloc: ^9.0.0

dev_dependencies:
  test: ^1.21.1
  purple_lints: ^0.5.0
